title:              My story begins here!
email:              salmonqawsed@gmail.com
description:        Venturing far from familiar shores, seeking answers, unlocking every door -- Joohyun Kim
author:             Joohyun Kim
baseurl:            ""
url:                "https://salmon0524.github.io"

# Social Profiles
twitter_username: salmon97523113
github_username: salmon0524
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
